server:
  port: 8080
spring:
  datasource:
    #password=Wing1Q2W#E
    username: root
    password: UxTHzDrOzpSFcyFT591pPS0EmMkP0OndpWa/lmxHnIasIEW+Nx8F29elcEvBjlmcnUn5XGFZGMSsBEXii/ed9w==
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://115.159.83.201:3306/jc-club?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&userSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey};
      min-idle: 20
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJj1cVTtec9WfICdXtdl0a+41HurnhADRcsayBVYFdEjUkLrx20bFYDafcly2iBvfLol5OD98F8jY/Yz+G/ntRsCAwEAAQ==
logging:
  config: classpath:log4j2-spring.xml
